spring:
  application:
    name: chat-online

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/chatapp?createDatabaseIfNotExist=true}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ${MYSQL_ROOT_PASSWORD:root}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

api:
  prefix: /api/v1

backend:
  url: http://localhost:8080